### ISSUE TITLE
Export PA VIIRS Data – April 9, 2014 to Present

### ISSUE THREAD

**Issue by ezys** [SkyTruth/heatmap#3]
Bloomberg researchers want an update on the VIIRS flaring data. I think we gave them all VIIRS detections (regardless of frequency) within the limits of Pennsylvania.

**Comment by ezys** [comment]
@redhog Looks like we don't have milestones set up on this repo, but can you do this at your earliest convenience? Export all VIIRS detections from April 9, 2014 to present in .csv or similar format.

**Comment by enriquetuya** [comment]
@ezys I'm creating a ticket for this on Benthos that we have a milestone for all data processing tickets. I'll link it to this ticket.

**Comment by ezys** [comment]
@enriquetuya Thanks. I appreciate it.

**Comment by redhog** [comment]
https://storage.googleapis.com/viirs.skytruth.org/viirs-2014-04-09--2015-07-17.zip

**Comment by ezys** [comment]
@redhog Bloomberg came back with a lot of questions about April 9 (the one overlapping day), and I have come to realize that there was at least some processing done to the earlier PA detections dataset that we provided them.

https://github.com/SkyTruth/tasks/issues/281#issuecomment-43051214

Can you replicate the procedure you used before and generate a file for the aforementioned dates? I'm sorry, I thought we just gave them raw detections last time...

**Comment by redhog** [comment]
Filter with same filter as visualization (min 3 detections within time window, temp. filter)

**Comment by pwoods25443** [comment]
@ezys we need to know which file was sent to them last time.  Can you dig that up?

**Comment by ezys** [comment]
Here is the data we shipped, along with the methodology that we finally shipped after much discussion in late June of last year...

[VIIRS_PA_Methodology_v2.docx](https://github.com/SkyTruth/heatmap/files/1068/VIIRS_PA_Methodology_v2.docx)

**Comment by ezys** [comment]
Delivered to Bloomberg.
