### ISSUE TITLE
VIIRS Map only current through July 30, 2015

### ISSUE THREAD

**Issue by ezys** [SkyTruth/heatmap#4]
From email:

Egil:

Do you know any reason why the viirs processing pipeline is not working?  Can you take a quick peek at the logs?

Paul

**Comment by enriquetuya** [comment]
@redhog please give a look to this issue tomorrow (September 3rd) and based on what is the issue we will see on the stand-up if we are going to work on this now or next sprint.

**Comment by redhog** [comment]
This was my fault... I broke the  cron job when doing the PA viirs export :/ I have fixed that now. The import is currently running.

**Comment by redhog** [comment]
Done :)

**Comment by enriquetuya** [comment]
@redhog could you provide more info where this cron job is running?

**Comment by redhog** [comment]
There are a whole bunch of cron jobs running under django@scraper.skytruth.org that does web scraping and generation.

ssh there and run crontab -l to see how it's setup

**Comment by redhog** [comment]
I don't think there is any wiki page for this though.
